CREATE TABLE animals(id INT GENERATED ALWAYS AS IDENTITY, name VARCHAR, date_of_birth DATE, escape_attempts INT, neutered BOOLEAN, weight_kg DECIMAL, PRIMARY KEY(id));

ALTER TABLE animals ADD COLUMN species VARCHAR;

CREATE TABLE owners(id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, full_name VARCHAR (250) NOT NULL, age INT NOT NULL);
CREATE TABLE species(id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name VARCHAR (250) NOT NULL);

ALTER TABLE animals ADD PRIMARY KEY (id);
ALTER TABLE animals DROP COLUMN species;
ALTER TABLE animals ADD COLUMN species_id INT REFERENCES species(id);
ALTER TABLE animals ADD COLUMN owner_id INT REFERENCES owners(id);